{% extends request.ajax ? "layout_blank.phtml" : "layout_default.phtml" %}
{% import "macro_functions.phtml" as mf %}
{% block meta_title %}{% trans 'Transactions' %}{% endblock %}
{% set active_menu = 'invoice' %}


{% block top_content %}
{% if request.show_filter %}
<div class="row-fluid">
<div class="span12">
						<!-- BEGIN TAB PORTLET-->   
						<div class="portlet box yellow tabbable">
							<div class="portlet-title">
								<h4><i class="icon-search"></i>{% trans 'Filter transactions' %}</h4>
							</div>
							<div class="portlet-body">
                         <BR />   

        <form method="get" action="" class="form-horizontal" style="margin:0px !important;">
            
             <div class="control-group">
                <label class="control-label">{% trans 'ID' %}</label>
                  <div class="controls">
                     <input type="text" name="id" value="{{ request.id }}">
                  </div>
            </div>
            
            <div class="control-group">
                <label class="control-label">{% trans 'ID on payment gateway' %}</label>
                  <div class="controls">
                     <input type="text" name="txn_id" value="{{ request.txn_id }}">
                  </div>
            </div>
            
            <div class="control-group">
                <label class="control-label">{% trans 'Invoice Id' %}</label>
                  <div class="controls">
                     <input type="text" name="invoice_id" value="{{ request.invoice_id }}">
                  </div>
            </div>

			<div class="control-group">
                <label class="control-label">{% trans 'Currency' %}</label>
                  <div class="controls">
                     {{ mf.selectbox('currency', guest.currency_get_pairs, request.currency, 0, 'All currencies') }}
                  </div>
            </div>

			<div class="control-group">
                <label class="control-label">{% trans 'Status' %}</label>
                  <div class="controls">
                     {{ mf.selectbox('status', admin.invoice_transaction_get_statuses_pairs, request.status, 0, 'All statuses') }}
                  </div>
            </div>

			<div class="control-group">
                <label class="control-label">{% trans 'Payment Gateway' %}:</label>
                  <div class="controls">
                     {{ mf.selectbox('gateway_id', admin.invoice_gateway_get_pairs, request.gateway_id, 0, 'All payment gateways') }}
                  </div>
            </div>
            
            
            <div class="control-group">
                              <label class="control-label">{% trans 'Received at' %}</label>
                              <div class="controls">
                                 <div class="input-append date date-picker" data-date="12-02-2012" data-date-format="dd-mm-yyyy" data-date-viewmode="years">
                                    <input class="m-wrap m-ctrl-medium date-picker" name="date_from" size="16" type="text" value="{% if request.date_from %}{{ request.date_from|date('Y-m-d') }}{%endif%}" placeholder="{{ now|date('Y-m-d') }}" /><span class="add-on"><i class="icon-calendar"></i></span>
                                 </div> 
                                  - 
                                 <div class="input-append date date-picker" data-date="12-02-2012" data-date-format="dd-mm-yyyy" data-date-viewmode="years">
                                    <input class="m-wrap m-ctrl-medium date-picker" name="date_to" size="16" type="text" value="{% if request.date_to %}{{ request.date_to|date('Y-m-d') }}{%endif%}" placeholder="{{ now|date('Y-m-d') }}" /><span class="add-on"><i class="icon-calendar"></i></span>
                                 </div> 
                                 
                              </div>
                           </div>
                           
                <div class="form-actions" style="margin-bottom:0px !important;">
                                    <input type="hidden" name="show_filter" value="1" />
                                    <input type="submit" value="{% trans 'Filter' %}" class="btn blue" />
                </div>

        </form>
        <div class="fix"></div>
    </div>
</div>
</div>
</div>
{% else %}
{% set statuses = admin.invoice_transaction_get_statuses %}
<div class="stats">
    <ul>
        <li><a href="{{ 'invoice/transactions'|alink }}?status=processed" class="count green" title="">{{ statuses.processed }}</a><span>{% trans 'Processed' %}</span></li>
        <li><a href="{{ 'invoice/transactions'|alink }}?status=approved" class="count blue" title="">{{ statuses.approved }}</a><span>{% trans 'Approved' %}</span></li>
        <li><a href="{{ 'invoice/transactions'|alink }}?status=error" class="count red" title="">{{ statuses.error }}</a><span>{% trans 'Error' %}</span></li>
        <li class="last"><a href="{{ 'invoice/transactions'|alink }}" class="count grey" title="">{{ statuses.received + statuses.approved + statuses.processed + statuses.error }}</a><span>{% trans 'Total' %}</span></li>
    </ul>
    <div class="fix"></div>
</div>
{% endif %}

{% endblock %}

{% block content %}
<br /><BR />
<div class="row-fluid">
<div class="span12">
						<!-- BEGIN SAMPLE TABLE PORTLET-->				
						<div class="portlet">
							<div class="portlet-title">
								<h4><i class="icon-cogs"></i>{% trans 'Transactions' %}</h4>
								<div class="tools">
									<a href="javascript:;" class="collapse"></a>
								</div>
							</div>
							<div class="portlet-body">
	
<br /><BR />{{ mf.table_search }}
    <table class="table table-striped table-bordered table-advance table-hover">
        <thead>
            <tr>
                <th width="5%">{% trans 'Invoice' %}</th>
                <th>{% trans 'Type' %}</th>
                <th>{% trans 'Status' %}</th>
                <th>{% trans 'Gateway' %}</th>
                <th>{% trans 'Amount' %}</th>
                <th>{% trans 'Date' %}</th>
                <th width="18%">&nbsp;</th>
            </tr>
        </thead>

        <tbody>
            {% set transactions = admin.invoice_transaction_get_list({"per_page":30, "page":request.page}|merge(request)) %}
            {% for i, tx in transactions.list %}
            <tr>
                <td>{% if tx.invoice_id %}<a href="{{ 'invoice/manage'|alink }}/{{tx.invoice_id}}">#{{ tx.invoice_id }}</a>{%else%}n/a{% endif %}</td>
                <td>{{mf.status_name(tx.type|default('-')) }}</td>
                <td>{% if tx.error %}<a href="#" onclick="bb.msg('{{ tx.error }}','{{ tx.error_code }}'); return false;">{{ tx.error_code }}</a>{% else %}{{mf.status_name(tx.status) }}{% endif %}</td>
                <td>{{tx.gateway}}</td>
                <td>{{ mf.currency_format( tx.amount, tx.currency) }}</td>
                <td>{{tx.created_at|date('Y-m-d H:i')}}</td>
                <td class="actions">
                    <a class="btn14" href="{{ 'invoice/transaction'|alink }}/{{ tx.id }}"><img src="images/icons/dark/pencil.png" alt=""></a>
                    <a class="btn14 api-link" href="admin/invoice/transaction_process?id={{ tx.id }}" data-api-msg="Processed" title="Process again"><img src="images/icons/dark/refresh4.png" alt=""></a>
                    <a class="btn14 bb-rm-tr api-link" href="admin/invoice/transaction_delete?id={{ tx.id }}" data-api-confirm="Are you sure?" data-api-reload="1"><img src="images/icons/dark/trash.png" alt=""></a>
                </td>
            </tr>
            {% else %}
            <tr>
                <td colspan="7">
                    {% trans 'The list is empty' %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
</div>
</div>
</div>
{% include "partial_pagination.phtml" with {'list': transactions, 'url':'invoice/transactions'} %}
{% endblock %}