{% extends request.ajax ? "layout_blank.phtml" : "layout_default.phtml" %}
{% set active_menu = 'invoice' %}
{% block meta_title %}Subscription {{ subscription.sid }}{% endblock %}

{% block content %}

<div style="padding-top:20px;"></div>
<div class="tabbable tabbable-custom">
											<ul class="nav nav-tabs">
												<li class="active"><a href="#tab_index" data-toggle="tab">{% trans 'Subscription' %}</a></li>
												<li><a href="#tab_manage" data-toggle="tab">{% trans 'New Manage' %}</a></li>
											</ul>
											<div class="tab-content">
												<div class="tab-pane active" id="tab_index">

            <div class="help">
                <h3>{% trans 'Subscription details' %}</h3>
            </div>

            <table class="table table-striped table-bordered table-advance table-hover" style="margin-top:0px !important; margin-bottom: 0px !important;">
                <tbody>
                    <tr class="noborder">
                        <td>{% trans 'Client' %}</td>
                        <td><a href="{{ 'client/manage'|alink }}/{{subscription.client.id}}">{{ subscription.client.first_name }} {{ subscription.client.last_name }}</a></td>
                    </tr>

                    <tr>
                        <td>{% trans 'Amount' %}</td>
                        <td>{{ mf.currency_format( subscription.amount, subscription.currency) }} {{ mf.period_name(subscription.period) }}</td>
                    </tr>

                    <tr>
                        <td>{% trans 'Payment gateway' %}</td>
                        <td>{{subscription.gateway.title}}</td>
                    </tr>

                    <tr>
                        <td>{% trans 'Subscription ID on payment gateway' %}</td>
                        <td>{{subscription.sid|default('-')}}</td>
                    </tr>

                    <tr>
                        <td>{% trans 'Status' %}</td>
                        <td>{{ mf.status_name(subscription.status) }}</td>
                    </tr>

                    <tr>
                        <td>{% trans 'Created at' %}</td>
                        <td>{{subscription.created_at|date('l, d F Y')}}</td>
                    </tr>

                    {% if subscription.created_at != subscription.updated_at %}
                    <tr>
                        <td>{% trans 'Updated at' %}</td>
                        <td>{{subscription.updated_at|date('l, d F Y')}}</td>
                    </tr>
                    {% endif %}
                 </tbody>

                 <tfoot>
                     <tr>
                         <td colspan="2">
                            <div class="aligncenter">
                                <a class="btn55 mr10 api-link" href="admin/invoice/subscription_delete?id={{subscription.id}}" data-api-confirm="Are you sure?" data-api-redirect="invoice/subscriptions"><img src="images/icons/middlenav/trash.png" alt=""><span>{% trans 'Delete' %}</span></a>
                            </div>
                         </td>
                     </tr>
                 </tfoot>
            </table>

        </div>

        <div id="tab_manage" class="tab-pane">
            <form method="post" action="admin/invoice/subscription_update" class="form-horizontal save api-form" data-api-reload="1">
            
            <div class="control-group">
                <label class="control-label">{% trans 'Payment Gateway' %}:</label>
                  <div class="controls">
                     {{ mf.selectbox('gateway_id', admin.invoice_gateway_get_pairs, subscription.gateway.id, 0, 'Select payment gateway') }}
                  </div>
            </div>
            
            <div class="control-group">
                <label class="control-label">{% trans 'Subscription ID on payment gateway' %}:</label>
                  <div class="controls">
                     <input type="text" name="sid" value="{{subscription.sid}}" required="required" placeholder=""/>
                  </div>
            </div>
            
            <div class="control-group">
                <label class="control-label">{% trans 'Status' %}:</label>
                  <div class="controls">
                    <label class="radio">
                      <div class="radio" id="uniform-undefined"><span><input type="radio" name="status" value="active" {% if subscription.status == 'active' %} checked="checked"{% endif %} style="opacity: 0;"></span></div>
                        {% trans 'Active' %}
                    </label>
                    <label class="radio">
                      <div class="radio" id="uniform-undefined"><span><input type="radio" name="status" value="canceled" {% if subscription.status == 'canceled' %} checked="checked"{% endif %} style="opacity: 0;"></span></div>{% trans 'Canceled' %}
                    </label>
                  </div>
            </div>

            <div class="control-group">
                <label class="control-label">{% trans 'Period' %}:</label>
                  <div class="controls">
                     {{ mf.selectbox('period', guest.system_periods, subscription.period, 1, 'Select period') }}
                  </div>
            </div>
            
            <div class="control-group">
                <label class="control-label">{% trans 'Amount' %}:</label>
                  <div class="controls">
                     <input type="text" name="amount" value="{{subscription.amount}}" required="required" placeholder=""/>
                  </div>
            </div>

            <div class="control-group">
                <label class="control-label">{% trans 'Currency' %}</label>
                  <div class="controls">
                     {{ mf.selectbox('currency', guest.currency_get_pairs, subscription.currency, 1, 'Select currency') }}
                  </div>
            </div>
            
            <div class="form-actions">
                <input type="submit" value="{% trans 'Update' %}" class="btn blue" />
                <input type="hidden" name="id" value="{{ subscription.id }}" />
            </div>
                    
            </form>
        </div>

    </div>

    <div class="fix"></div>
</div>
  </div>
    </div>
{% endblock %}