{% extends request.ajax ? "layout_blank.phtml" : "layout_default.phtml" %}
{% import "macro_functions.phtml" as mf %}
{% block meta_title %}{% trans 'Invoice' %} {{ invoice.serie }}{{ "%05s"|format(invoice.nr) }}{% endblock %}
{% set active_menu = 'invoice' %}


{% block breadcrumbs %}
						<ul class="breadcrumb">
							<li>
								<i class="icon-home"></i>
								<a href="{{ '/'|alink }}">{% trans 'Home' %}</a> 
								<span class="icon-angle-right"></span>
							</li>
                             <li><a href="{{ 'invoice'|alink }}">{% trans 'Invoices' %}</a>
                             <span class="icon-angle-right"></span></li>
							<li>{{ invoice.serie }}{{ "%05s"|format(invoice.nr) }}</li>
						</ul>
{% endblock %}


{% block content %}

<div class="row-fluid">
<div class="span12">
						<!-- BEGIN TAB PORTLET-->   
						<div class="portlet box yellow tabbable">
							<div class="portlet-title">
								<h4><i class="icon-reorder"></i>{% trans 'Order management' %}</h4>
							</div>
							<div class="portlet-body">
								<div class="tabbable portlet-tabs">
									<ul class="nav nav-tabs">
                                        <li><a href="#tab-seller-credentials" data-toggle="tab">Company credentials</a></li>
                                        <li><a href="#tab-buyer-credentials" data-toggle="tab">Client credentials</a></li>
                                        <li><a href="#tab-texts" data-toggle="tab">Texts</a></li>
                                        <li><a href="#tab-manage" data-toggle="tab">Manage</a></li>
                                        <li class="active"><a href="#tab-info" data-toggle="tab">{% trans 'Details' %}</a></li>
									</ul>
									<div class="tab-content">
										<div class="tab-pane active" id="tab-info">

                <table class="table table-bordered table-hover" style="padding:0px !important; min-height:0px important;">
                    <tbody>
                    <tr class="noborder">
                        <td style="width: 20%"><label>{% trans 'ID' %}</label></td>
                        <td>{{ invoice.id }}</td>
                    </tr>
                    <tr>
                        <td><label>{% trans 'Number' %}</label></td>
                        <td>{{ invoice.serie }}{{ "%05s"|format(invoice.nr) }}</td>
                    </tr>
                    <tr>
                        <td><label>{% trans 'Currency' %}</label></td>
                        <td>{{ invoice.currency }}</td>
                    </tr>
                    <tr>
                        <td><label>{% trans 'Client' %}</label></td>
                        <td><a href="{{ 'client/manage'|alink }}/{{ invoice.client.id }}">{{ invoice.client.first_name }} {{ invoice.client.last_name }}</a></td>
                    </tr>

                    <tr>
                        <td><label>{% trans 'Status' %}</label></td>
                        <td>{{ mf.status_name(invoice.status) }}</td>
                    </tr>

                    {% if invoice.tax %}
                    <tr>
                        <td><label>{{ invoice.taxname }} {{ invoice.taxrate }}%</label></td>
                        <td>{{ mf.currency_format(invoice.tax, invoice.currency) }}</td>
                    </tr>
                    {% endif %}
                    
                    <tr>
                        <td><label>{% trans 'Total' %}</label></td>
                        <td>{{ mf.currency_format(invoice.total, invoice.currency) }}</td>
                    </tr>
                    
                    <tr>
                        <td><label>{% trans 'Created at' %}</label></td>
                        <td>{{ invoice.created_at|date }}</td>
                    </tr>

                    <tr>
                        <td><label>{% trans 'Due at' %}</label></td>
                        <td>{{ invoice.due_at|date }}</td>
                    </tr>

                    <tr>
                        <td><label>{% trans 'Paid at' %}</label></td>
                        <td>{% if invoice.paid_at %}{{ invoice.paid_at|date }}{% else %}-{% endif %}</td>
                    </tr>

                    <tr>
                        <td><label>{% trans 'Reminded at' %}</label></td>
                        <td>{% if invoice.reminded_at %}{{ invoice.reminded_at|date }} ({{invoice.reminded_at|timeago}} ago) {% endif %}</td>
                    </tr>
                    
                    {% if invoice.notes %}
                    <tr>
                        <td><label>{% trans 'Notes' %}</label></td>
                        <td>{{ invoice.notes|bbmd }}</td>
                    </tr>
                    {% endif %}
                    </tbody>
                    
                    <tfoot>
                        <tr>
                            <th colspan="2">
                                <div class="aligncenter">
                                    <a href="{{ 'invoice'|link }}/{{ invoice.hash }}" title="" class="btn55 mr10" target="_blank"><img src="images/icons/middlenav/preview.png" alt=""><span>View as client</span></a>
                                    <a href="admin/invoice/delete?id={{invoice.id}}" data-api-confirm="Are you sure?"  title="" class="btn55 mr10 api-link" data-api-redirect="invoice"><img src="images/icons/middlenav/trash.png" alt=""><span>Delete</span></a>
                                    {% if invoice.status == 'unpaid' %}
                                    <a href="admin/invoice/send_reminder?id={{invoice.id}}" title="" class="btn55 mr10 api-link" data-api-msg="Payment reminder was sent"><img src="images/icons/middlenav/mail.png" alt=""><span>Send reminder</span></a>
                                    <a href="admin/invoice/mark_as_paid?id={{invoice.id}}&execute=1" title="" class="btn55 mr10 api-link" data-api-reload="Invoice marked as paid"><img src="images/icons/middlenav/play2.png" alt=""><span>Mark as paid</span></a>
                                    {% endif %}
                                    
                                    {% if invoice.status == 'paid' %}
                                    <a href="admin/invoice/refund?id={{invoice.id}}" data-api-confirm="Are you sure?"  title="" class="btn55 mr10 api-link" data-api-redirect="invoice"><img src="images/icons/middlenav/refresh4.png" alt=""><span>Refund</span></a>
                                    {% endif %}
                                </div>
                            </td>
                        </tr>
                    </tfoot>
                </table>
            </div>

   

        <div class="tab-pane" id="tab-manage">
            <form action="admin/invoice/update" method="post" class="form-horizontal api-form" data-api-reload="Invoice updated">
            
            
            <div class="control-group">
           <label class="control-label">{% trans 'Status' %}</label>
            <div class="controls">
                        
            <label class="radio">
              <div class="radio" id="uniform-undefined"><span><input type="radio" name="status" value="paid"{% if invoice.status == 'paid' %} checked="checked"{% endif %} style="opacity: 0;"></span></div>
                {% trans 'Paid' %}
            </label>
            
            <label class="radio">
              <div class="radio" id="uniform-undefined"><span><input type="radio" name="status" value="unpaid"{% if invoice.status == 'unpaid' %} checked="checked"{% endif %} style="opacity: 0;"></span></div>
                {% trans 'Unpaid' %}
            </label>
            
            <label class="radio">
              <div class="radio" id="uniform-undefined"><span><input type="radio" name="status" value="refunded"{% if invoice.status == 'refunded' %} checked="checked"{% endif %} style="opacity: 0;"></span></div>
                {% trans 'Refunded' %}
            </label>  
            
            <label class="radio">
              <div class="radio" id="uniform-undefined"><span><input type="radio" name="status" value="canceled"{% if invoice.status == 'canceled' %} checked="checked"{% endif %} style="opacity: 0;"></span></div>
                {% trans 'Refunded' %}
            </label>                                   

            </div>
          </div>
            
		  <div class="control-group">
           <label class="control-label">{% trans 'Approved' %}</label>
            <div class="controls">
                        
            <label class="radio">
              <div class="radio" id="uniform-undefined"><span><input type="radio" name="approved" value="0"{% if invoice.approved %} checked="checked"{% endif %} style="opacity: 0;"></span></div>
                Yes
            </label>
            
            <label class="radio">
              <div class="radio" id="uniform-undefined"><span><input type="radio" name="approved" value="1"{% if not invoice.approved %} checked="checked"{% endif %} style="opacity: 0;"></span></div>
                No
            </label>
            
            </div>
          </div>

          <div class="control-group">
           <label class="control-label">{% trans 'Serie and number' %}:</label>
            <div class="controls">

                <input type="text" name="serie" value="{{ invoice.serie }}"/> <input type="text" name="nr" value="{{ invoice.nr }}"/>

            </div>
          </div> 
          
          <div class="control-group">
           <label class="control-label">{% trans 'Tax' %}:</label>
            <div class="controls">

             <input type="text" name="taxname" value="{{ invoice.taxname }}"/> <input type="text" name="taxrate" value="{{ invoice.taxrate }}"/> %

            </div>
          </div> 
          

		  <div class="control-group">
           <label class="control-label">{% trans 'Payment method' %}:</label>
            <div class="controls">

             {{ mf.selectbox('gateway_id', guest.invoice_gateways({"format":"pairs"}), invoice.gateway_id, 0, 'Select payment method') }}

            </div>
          </div> 

		  <div class="control-group">
           <label class="control-label">{% trans 'Created at' %}:</label>
            <div class="controls">
				
                <div class="input-append date date-picker" data-date="12-02-2012" data-date-format="dd-mm-yyyy" data-date-viewmode="years">
                 <input class="m-wrap m-ctrl-medium date-picker" name="created_at" size="16" type="text" value="{{ invoice.created_at|date('Y-m-d') }}" /><span class="add-on"><i class="icon-calendar"></i></span>
                </div> 

            </div>
          </div> 

		  <div class="control-group">
           <label class="control-label">{% trans 'Due at' %}:</label>
            <div class="controls">
				
                <div class="input-append date date-picker" data-date="12-02-2012" data-date-format="dd-mm-yyyy" data-date-viewmode="years">
                 <input class="m-wrap m-ctrl-medium date-picker" name="due_at" size="16" type="text" value="{% if invoice.due_at %}{{ invoice.due_at|date('Y-m-d') }}{% endif %}" /><span class="add-on"><i class="icon-calendar"></i></span>
                </div> 

            </div>
          </div> 

		  <div class="control-group">
           <label class="control-label">{% trans 'Paid at' %}:</label>
            <div class="controls">
				
                <div class="input-append date date-picker" data-date="12-02-2012" data-date-format="dd-mm-yyyy" data-date-viewmode="years">
                 <input class="m-wrap m-ctrl-medium date-picker" name="paid_at" size="16" type="text" value="{% if invoice.paid_at %}{{ invoice.paid_at|date('Y-m-d') }}{% endif %}" /><span class="add-on"><i class="icon-calendar"></i></span>
                </div> 

            </div>
          </div>

		  <div class="control-group">
           <label class="control-label">{% trans 'Notes' %}:</label>
            <div class="controls">
				
                <textarea name="notes" class="span12 wysihtml5 m-wrap" cols="5" rows="6">{{ invoice.notes }}</textarea>

            </div>
          </div>

			<div class="form-actions">
                <input type="submit" value="{% trans 'Update' %}" class="btn blue" />
                <input type="hidden" name="id" value="{{ invoice.id }}" />
            </div>

            </form>
        </div>

        <div class="tab-pane" id="tab-texts">
            <form action="admin/invoice/update" method="post" class="form-horizontal api-form" data-api-msg="Invoice updated">
            
            <div class="control-group">
                              <label class="control-label">{% trans 'Text before invoice items table' %}</label>
                              <div class="controls">
                                 <textarea name="text_1"  cols="5" rows="6" class="span12 bb-textarea"/>{{ invoice.text_1 }}</textarea>
                              </div>
            </div>
            
            
            <div class="control-group">
                              <label class="control-label">{% trans 'Text after invoice items table' %}</label>
                              <div class="controls">
                                 <textarea name="text_2"  cols="5" rows="6" class="span12 bb-textarea"/>{{ invoice.text_1 }}</textarea>
                              </div>
            </div>

                
			<div class="form-actions">
                <input type="submit" value="{% trans 'Update' %}" class="btn blue" />
                <input type="hidden" name="id" value="{{ invoice.id }}" />
            </div>
           
            </form>

            <div class="fix"></div>
        </div>

        <div class="tab-pane" id="tab-seller-credentials">
            {% set seller = invoice.seller %}
            <form action="admin/invoice/update" method="post" class="form-horizontal api-form" data-api-msg="Invoice updated">
                <h3 class="block">Company details at the moment of purchase</h3>


			<div class="control-group">
                <label class="control-label">{% trans 'Company' %}:</label>
                  <div class="controls">
                     <input type="text" name="seller_company" value="{{ seller.company }}"/>
                  </div>
            </div>

			<div class="control-group">
                <label class="control-label">{% trans 'Company VAT' %}:</label>
                  <div class="controls">
                     <input type="text" name="seller_company_vat" value="{{ seller.company_vat }}"/>
                  </div>
            </div>
            
			<div class="control-group">
                <label class="control-label">{% trans 'Company Number' %}:</label>
                  <div class="controls">
                     <input type="text" name="seller_company_number" value="{{ seller.company_number }}"/>
                  </div>
            </div>                     
                    
			<div class="control-group">
                <label class="control-label">{% trans 'Address' %}:</label>
                  <div class="controls">
                     <input type="text" name="seller_address" value="{{ seller.address }}"/>
                  </div>
            </div>

			<div class="control-group">
                <label class="control-label">{% trans 'Phone' %}:</label>
                  <div class="controls">
                     <input type="text" name="seller_phone" value="{{ seller.phone }}"/>
                  </div>
            </div>

			<div class="control-group">
                <label class="control-label">{% trans 'Email' %}:</label>
                  <div class="controls">
                     <input type="text" name="seller_email" value="{{ seller.email }}"/>
                  </div>
            </div>
            
			<div class="form-actions">
                <input type="submit" value="{% trans 'Update' %}" class="btn blue" />
                <input type="hidden" name="id" value="{{ invoice.id }}" />
            </div>

            </form>

        </div>


        <div class="tab-pane" id="tab-buyer-credentials">
            {% set buyer = invoice.buyer %}
            <form action="admin/invoice/update" method="post" class="form-horizontal api-form" data-api-msg="Invoice updated">
                <h3 class="block">Client details at the moment of purchase</h3>

			<div class="control-group">
                <label class="control-label">{% trans 'First name' %}:</label>
                  <div class="controls">
                     <input type="text" name="buyer_first_name" value="{{ buyer.first_name }}"/>
                  </div>
            </div>
            
			<div class="control-group">
                <label class="control-label">{% trans 'Last name' %}:</label>
                  <div class="controls">
                     <input type="text" name="buyer_last_name" value="{{ buyer.last_name }}"/>
                  </div>
            </div>
            
			<div class="control-group">
                <label class="control-label">{% trans 'Company' %}:</label>
                  <div class="controls">
                     <input type="text" name="buyer_company" value="{{ buyer.company }}"/>
                  </div>
            </div>
            
			<div class="control-group">
                <label class="control-label">{% trans 'Company VAT' %}:</label>
                  <div class="controls">
                     <input type="text" name="buyer_company_vat" value="{{ buyer.company_vat }}"/>
                  </div>
            </div>
            
			<div class="control-group">
                <label class="control-label">{% trans 'Company Number' %}:</label>
                  <div class="controls">
                     <input type="text" name="buyer_company_number" value="{{ buyer.company_number }}"/>
                  </div>
            </div>
            
			<div class="control-group">
                <label class="control-label">{% trans 'Address' %}:</label>
                  <div class="controls">
                     <input type="text" name="buyer_address" value="{{ buyer.address }}"/>
                  </div>
            </div>
                    
			<div class="control-group">
                <label class="control-label">{% trans 'City' %}:</label>
                  <div class="controls">
                     <input type="text" name="buyer_city" value="{{ buyer.city }}"/>
                  </div>
            </div>

			<div class="control-group">
                <label class="control-label">{% trans 'State' %}:</label>
                  <div class="controls">
                     {# mf.selectbox('buyer_state', guest.system_states, buyer.state, 0, 'Select state') #}
                     <input type="text" name="buyer_state" value="{{ buyer.state }}" />
                  </div>
            </div>
            
			<div class="control-group">
                <label class="control-label">{% trans 'Country' %}:</label>
                  <div class="controls">
                     {{ mf.selectbox('buyer_country', guest.system_countries, buyer.country, 0, 'Select country') }}
                  </div>
            </div>

			<div class="control-group">
                <label class="control-label">{% trans 'Phone' %}:</label>
                  <div class="controls">
                     <input type="text" name="buyer_phone" value="{{ buyer.phone }}"/>
                  </div>
            </div>
            
            <div class="control-group">
                <label class="control-label">{% trans 'Zip' %}:</label>
                  <div class="controls">
                     <input type="text" name="buyer_zip" value="{{ buyer.zip }}"/>
                  </div>
            </div>
            
            <div class="control-group">
                <label class="control-label">{% trans 'Email' %}:</label>
                  <div class="controls">
                     <input type="text" name="buyer_email" value="{{ buyer.email }}"/>
                  </div>
            </div>

			<div class="form-actions">
                <input type="submit" value="{% trans 'Update' %}" class="btn blue" />
                <input type="hidden" name="id" value="{{ invoice.id }}" />
            </div>

            </form>

            <div class="fix"></div>
        </div>

    </div>
</div>
</div>
</div></div></div>

<div class="row-fluid">
<div class="span12">
						<!-- BEGIN TAB PORTLET-->   
						<div class="portlet box yellow tabbable">
							<div class="portlet-title">
								<h4><i class="icon-reorder"></i>{% trans 'Invoice items' %}</h4>
							</div>
							<div class="portlet-body">


{% if not invoice.approved %}

    <form action="admin/invoice/update" method="post" class="form-horizontal api-form" data-api-reload="1" style="margin-bottom:0px !important;">
    
        <table class="table table-striped table-bordered table-advance table-hover" style="margin-top:0px !important; margin-bottom: 0px !important;">
            <thead>
                <tr>
                    <th>{% trans 'Title' %}</th>
                    <th class="currency">{% trans 'Price' %}</th>
                    <th>{% trans 'Tax' %}</th>
                    <th class="actions">&nbsp;</th>
                </tr>
            </thead>

            <tbody>
                {% for i, item in invoice.lines %}
                <tr>
                    <td style="width: 60%;"><input type="text" name="items[{{ item.id }}][title]" value="{{ item.title }}" style="width:98%"></td>
                    <td style="width: 20%;"><input type="text" name="items[{{ item.id }}][price]" value="{{ item.price }}" style="width:80px"> {{ invoice.currency }}</td>
                    <td style="width: 5%;">
                        <input type="checkbox" name="items[{{ item.id }}][taxed]" value="1" {% if item.taxed %}checked="checked"{% endif %}/>
                    </td>
                    <td style="width: 10%;">
                        <a class="btn mini black api-link" data-api-confirm="Are you sure?" href="admin/invoice/item_delete?id={{item.id}}" data-api-reload="1" style="width: 60px;"><i class="icon-trash"></i> {% trans 'Delete' %}</a>
                    </td>
                </tr>
                {% endfor %}

                <tr>
                    <td style="width: 70%;"><input type="text" name="new_item[title]" value="" style="width:98%" placeholder="New line description"></td>
                    <td style="width: 20%;"><input type="text" name="new_item[price]" value="" style="width:80px" placeholder="Price"> {{ invoice.currency }}</td>
                    <td><input type="checkbox" name="new_item[taxed]" value="1"/></td>
                    <td>&nbsp;</td>
                </tr>
            </tbody>

            <tfoot>
                <tr>
                    <td colspan="4" class="currency">
                        Subtotal: {{ mf.currency_format(invoice.subtotal, invoice.currency) }}
                    </td>
                </tr>
                <tr>
                    <td colspan="4" class="currency">
                        {{ invoice.taxname }} {{ invoice.taxrate }}%: {{ mf.currency_format(invoice.tax, invoice.currency) }}
                    </td>
                </tr>
                <tr>
                    <td colspan="4" class="currency">
                        Total: {{ mf.currency_format(invoice.total, invoice.currency) }}
                    </td>
                </tr>
                <tr>
                    <td colspan="4">
                        {% if not invoice.approved %}
                        <a href="admin/invoice/approve?id={{invoice.id}}"  title="" class="btnIconLeft mr10 api-link" data-api-reload="{{ 'invoices'|alink }}"><img src="images/icons/dark/check.png" alt="" class="icon"><span>Approve</span></a>
                        {% endif %}
                        <input type="submit" value="{% trans 'Update' %}" class="greyishBtn submitForm" style="width:100px"/>
                    </td>
                </tr>
            </tfoot>
        </table>

        <input type="hidden" name="id" value="{{ invoice.id }}" />
    </form>

{% else %}
    <table class="table table-striped table-bordered table-advance table-hover" style="margin-top:0px !important; margin-bottom: 0px !important;">
        <thead>
            <tr>
                <th  style="width: 11%;" colspan="2"></th>
                <th style="width: 70%;">{% trans 'Title' %}</th>
                <th style="width: 7%;">{% trans 'Tax' %}</th>
                <th class="currency" style="width: 15%;">{% trans 'Total' %}</th>
            </tr>
        </thead>

        <tbody>
            {% for i, item in invoice.lines %}

            <tr>
                <td>{{ i+1 }}.</td>
                <td>
                    <div class="bull task {{ item.status }}" title="Task status: {{ mf.status_name(item.status) }}"></div>
                    <div class="bull charge {{ item.charged ? 'yes' : 'no' }}" title="{{ item.charged ? 'Charged from client balance' : 'Not charged from client balance' }}"></div>
                </td>
                <td>
                {% if item.order_id %}
                <a href="{{ 'order/manage'|alink }}/{{ item.order_id }}">{{ item.title }} {% if item.quantity > 1 %} x {{ item.quantity }} {# item.unit #}{% endif %}</a>
                {% else %}
                {{ item.title }} {% if item.quantity > 1 %} x {{ item.quantity }} {# item.unit #}{% endif %}
                {% endif %}
                </td>
                <td>{{ mf.currency_format(item.tax,invoice.currency) }}</td>
                <td class="currency">{{ mf.currency_format( item.total, invoice.currency) }}</td>
            </tr>

            {% endfor %}
        </tbody>
        
        <tfoot>
            <tr>
                <td colspan="5" class="currency">
                    Subtotal: {{ mf.currency_format(invoice.subtotal, invoice.currency) }}
                </td>
            </tr>
            <tr>
                <td colspan="5" class="currency">
                    {{ invoice.taxname }} {{ invoice.taxrate }}%: {{ mf.currency_format(invoice.tax, invoice.currency) }}
                </td>
            </tr>
            <tr>
                <td colspan="5" class="currency">
                    Total: {{ mf.currency_format(invoice.total, invoice.currency) }}
                </td>
            </tr>
        </tfoot>
    </table>
{% endif %}

</div>
</div>
</div>
</div>

{% set transactions = admin.invoice_transaction_get_list({"invoice_id":invoice.id,"per_page":100 }).list %}

{% if transactions|length > 0 %}

<div class="row-fluid">
<div class="span12">
						<!-- BEGIN TAB PORTLET-->   
						<div class="portlet box yellow tabbable">
							<div class="portlet-title">
								<h4><i class="icon-reorder"></i>{% trans 'Transactions' %}</h4>
							</div>
							<div class="portlet-body">


    <table class="table table-striped table-bordered table-advance table-hover" style="margin-top:0px !important; margin-bottom: 0px !important;">
        <thead>
            <tr>
                <th>{% trans 'ID' %}</th>
                <th>{% trans 'Type' %}</th>
                <th>{% trans 'Gateway' %}</th>
                <th>{% trans 'Amount' %}</th>
                <th>{% trans 'Status' %}</th>
                 <th>{% trans 'Date' %}</th>
                <th>&nbsp;</th>
            </tr>
        </thead>

        <tbody>
            {% for i, tx in transactions %}
            <tr>
                <td>{{tx.txn_id}}</td>
                <td>{{tx.type}}</td>
                <td>{{tx.gateway}}</td>
                <td>{{ mf.currency_format( tx.amount, tx.currency) }}</td>
                <td>{{ mf.status_name(tx.status) }}</td>
                <td>{{tx.created_at|bb_datetime}}</td>
                <td style="width: 5%">
                <a href="{{ '/invoice/transaction'|alink }}/{{tx.id}}" class="btn mini purple"><i class="icon-edit"></i> {% trans 'Edit' %}</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
</div>
</div>
</div>

{% endif %}

{% endblock %}

{% block sidebar2 %}

<div class="widget">
    <div class="head">
        <h2 class="dark-icon i-services">{% trans 'Actions' %}</h2>
    </div>
    <div class="block">
        <button class="bb-button" type="button" onclick="window.print()"><span class="dark-icon i-print"></span> {% trans 'Print' %}</button>
        {% if invoice.status == 'unpaid' %}
        <a class="bb-button api-link" href="client/invoice/delete?hash={{invoice.hash}}"  data-api-confirm="Are you sure?" data-api-redirect="{{ 'invoice'|link }}"><span class="dark-icon i-bin"></span> {% trans 'Delete' %}</a>
        {% endif %}
    </div>
</div>


{% endblock %}

{% block head %}{{ mf.bb_editor('.bb-textarea') }}{% endblock %}
{% block js %}
{% autoescape true js %}
<script type="text/javascript">
$(function() {
    $('input[name=gateway]:first').attr('checked', true);
    $('#pay-now-button').click(function(){
        var link = $('input[name=gateway]:checked').val();
        bb.redirect(link);
        return false;
    });
});
</script>
{% endautoescape %}
{% endblock %}