{% extends "layout_login.phtml" %}

{% block meta_title %}{% trans 'Login' %}{% endblock %}

{% block content %}

    <!-- BEGIN LOGIN FORM -->
    <form class="form-vertical login-form api-form" action="guest/staff/login" method="post" data-api-redirect="index" />
      <h3 class="form-title">{% trans 'Login' %}</h3>
      <div class="control-group">
        <div class="controls">
          <div class="input-icon left">
            <i class="icon-user"></i>
            <input class="m-wrap" type="email" name="email" value="{{ request.email }}" placeholder="{% trans 'Enter your email address' %}" id="req1" />
          </div>
        </div>
      </div>
      <div class="control-group">
        <div class="controls">
          <div class="input-icon left">
            <i class="icon-lock"></i>
            <input class="m-wrap" id="req2" type="password" name="password" value="{{ request.password }}" placeholder="{% trans 'Enter your password' %}" />
          </div>
        </div>
      </div>
      <div class="form-actions">
        <label class="checkbox">
        <input type="checkbox" id="remember" name="remember" value="1" checked="checked" /> {% trans 'Remember me' %}
        </label>            
		<input type="submit" value="{% trans 'Log me in' %}" class="btn green pull-right" />
      </div>
    </form>
    <!-- END LOGIN FORM --> 


{% endblock %}
