{% extends "layout_default.phtml" %}
{% set active_menu = 'products' %}
{% block meta_title %}{% trans 'Products' %}{% endblock %}

{% block content %}
<div style="padding-top:20px;"></div>
<div class="tabbable tabbable-custom">
											<ul class="nav nav-tabs">
                                                <li class="active"><a href="#tab_index" data-toggle="tab">{% trans 'Products' %}</a></li>
                                                <li><a href="#tab_new" data-toggle="tab">{% trans 'New product' %}</a></li>
                                                <li><a href="#tab_new_category" data-toggle="tab">{% trans 'New category' %}</a></li>
                                                <li><a href="#tab_categories" data-toggle="tab">{% trans 'Manage categories' %}</a></li>
											</ul>
											<div class="tab-content">
												<div class="tab-pane active" id="tab_index">
            <br /><br />{{ mf.table_search }}
            <form method="post" action="admin/product/update_priority" class="form-horizontal api-form" data-api-reload="1">

            <table class="table table-bordered table-hover" style="padding:0px !important; min-height:0px important;">
                <thead>
                    <tr>
                        <th width="50%">{% trans 'Title' %}</th>
                        <th>{% trans 'Status' %}</th>
                        <th>{% trans 'Category' %}</th>
                        <th width="10%">{% trans 'Type' %}</th>
                        <th style="width: 5%">{% trans 'Priority' %}</th>
                        <th width="13%">&nbsp;</th>
                    </tr>
                </thead>
                <tbody>
                    {% set products = admin.product_get_list({"per_page":30, "page":request.page}|merge(request)) %}
                    {% for product in products.list %}
                    <tr>
                        <td><a href="{{ '/product/manage'|alink }}/{{product.id}}">{{ product.title }}</a></td>
                        <td>{{ mf.status_name(product.status) }}</td>
                        <td><a href="{{ '/product/category'|alink }}/{{product.category.id}}">{{product.category.title}}</a></td>
                        <td>{{ mf.status_name(product.type) }}</td>
                        <td><input type="text" name="priority[{{product.id}}]" value="{{ product.priority }}" style="width:30px;"></td>
                        <td class="actions">
                            <a class="bb-button btn14" href="{{ '/product/manage'|alink }}/{{product.id}}"><img src="images/icons/dark/pencil.png" alt=""></a>
                            <a class="bb-button btn14 bb-rm-tr api-link" data-api-confirm="Are you sure?" href="admin/product/delete?id={{product.id}}" data-api-redirect="product"><img src="images/icons/dark/trash.png" alt=""></a>
                        </td>
                    </tr>
                    {% else %}
                    <tr>
                        <td colspan="6">{% trans 'The list is empty' %}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
                
            {% include "partial_pagination.phtml" with {'list': products, 'url':'product'} %}
            
            <div class="form-actions">
               <input type="submit" value="{% trans 'Update priority' %}" class="btn blue">
            </div>
            
            </form>
        </div>

        <div class="tab-pane" id="tab_new">
            <form method="post" action="admin/product/prepare" class="form-horizontal" id="prepare-product">
                  <div class="control-group">
                   <label class="control-label">{% trans 'Type' %}:</label>
                    <div class="controls">
                       {{ mf.selectbox('type', admin.product_get_types, request.type, 1) }}
                    </div>
                  </div> 
                  
                  <div class="control-group">
                   <label class="control-label">{% trans 'Category' %}:</label>
                    <div class="controls">
                       {{ mf.selectbox('product_category_id', admin.product_category_get_pairs, request.product_category_id, 1) }}
                    </div>
                  </div> 

				  <div class="control-group">
                   <label class="control-label">{% trans 'Title' %}:</label>
                    <div class="controls">
                       <input type="text" name="title" value="{{request.title}}" required="required" placeholder=""/>
                    </div>
                  </div> 

				  <div class="form-actions">
                     <input type="submit" value="{% trans 'Create' %}" class="btn blue">
                   </div>

            </form>

            <div class="fix"></div>
        </div>

        <div class="tab-pane" id="tab_new_category">

            <form method="post" action="admin/product/category_create" class="form-horizontal save api-form" data-api-redirect="product">
                <div class="control-group">
                   <label class="control-label">{% trans 'Title' %}:</label>
                    <div class="controls">
                       <input type="text" name="title" value="{{request.cat_title}}" required="required"/>
                    </div>
                  </div>
                  
                  <div class="control-group">
                   <label class="control-label">{% trans 'Icon URL' %}:</label>
                    <div class="controls">
                       <input type="text" name="icon_url" value=""/>
                    </div>
                  </div>
                  
                  <div class="control-group">
                   <label class="control-label">{% trans 'Description' %}:</label>
                    <div class="controls">
                       <textarea name="description" cols="5" rows="4">{{request.cat_description}}</textarea>
                    </div>
				  </div>

					<div class="form-actions">
                     <input type="submit" value="{% trans 'Create' %}" class="btn blue">
                   </div>
                   
            </form>
        </div>

        <div class="tab-pane" id="tab_categories">
            <table class="tableStatic wide">
                <tbody>
                    {% for cat_id, cat_title in admin.product_category_get_pairs %}
                    <tr {% if loop.first %}class="noborder"{% endif %}>
                        <td>{{cat_title}}</td>
                        <td class="actions" style="width:13%">
                            <a class="bb-button btn14" href="{{ '/product/category'|alink }}/{{cat_id}}"><img src="images/icons/dark/pencil.png" alt=""></a>
                            <a class="bb-button btn14 bb-rm-tr api-link" data-api-confirm="Are you sure?" href="admin/product/category_delete?id={{cat_id}}" data-api-redirect="product"><img src="images/icons/dark/trash.png" alt=""></a>
                        </td>
                    </tr>
                    {% else %}
                    <tr>
                        <td colspan="3">{% trans 'The list is empty' %}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

    </div>

</div>

{% endblock %}

{% block js %}
<script type="text/javascript">
$(function() {

    $('#prepare-product').bind('submit', function(){
        api.post(
            $(this).attr('action'),
            $(this).serialize(),
            function(result) {
                bb.redirect('{{"product/manage/"}}' + result);
            }
        );
        return false;
    });
});
</script>
{% endblock %}